stages:
  - test
  - build
  - deploy

.test: &test
  stage: test
  image: node:14.17.0
  tags:
    - docker
  cache:
    paths:
      - node_modules
  before_script:
    - yarn install
  script:
    - yarn check:tsc
    - yarn check:lint
  artifacts:
    paths:
      - node_modules

.build: &build
  stage: build
  image: node:14.17.0
  tags:
    - docker
  script:
    - yarn build
  artifacts:
    paths:
      - build

.deploy: &deploy
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws s3 sync ./build s3://etz-dev-landing/ --delete

develop:test:
  extends: .test
  only:
    - develop

develop:build:
  extends: .build
  needs: ["develop:test"]
  only:
    - develop

develop:deploy:
  extends: .deploy
  needs: ["develop:build"]
  only:
    - develop
  when: on_success