[build]
  command = "yarn build"
  publish = "build/src"
  functions = "build/netlify/functions"

[[redirects]]
  from = "/asset/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[dev]
  framework = "#custom"
  command = "yarn dev"
  targetPort = 1234
  port = 8888
  publish = "build/src"
